version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/data_ingester/data_ingester_workspace"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/data_ingester/data_ingester_workspace/terraform/red"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
