        [package]
name = "msgraph_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph-rs-sdk = { git = "https://github.com/akinnane/graph-rs-sdk.git", features = ["rustls-tls"] }
tokio = { version = "1.25.0", features = ["full"] }
serde_json = "*"
reqwest = {version = "*", features = ["rustls-tls"]}
serde = { version = "1.0", features = ["derive"] }
futures = "*"
serde_with = "*"
itertools = "*"
azure_security_keyvault = { version = "*", default-features = false,  features = ["enable_reqwest_rustls"]}
azure_identity = { version = "*", default-features = false, features = ["enable_reqwest_rustls"]}
azure_core = { version = "*", default-features = false, features = ["enable_reqwest_rustls"]}
warp = "*"
openssl-sys = {version = "*", features=["vendored"]}
bytes = "*"
hyper = "*"
hostname = "*"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]


[profile.release]
strip = true
# lto = true

