[package]
name = "data_ingester_terraform"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
anyhow = "*"

[lints]
workspace = true
