pub mod msgraph_data;
pub mod ms_graph;
pub mod admin_request_consent_policy;
pub mod conditional_access_policies;
pub mod groups;
pub mod users;
pub mod roles;
pub mod security_score;
pub mod directory_roles;
