---
name: Data Ingester Azure Terraform

on:
  push:
    paths:
      - data_ingester/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

        # Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          default: true
          components: rust-src, clippy

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0

      - name: cargo audit
        run: cargo install cargo-audit; cd data_ingester/data_ingester_workspace; cargo audit


      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            data_ingester/data_ingester_workspace/target
          key: cache-rust-target-${{ hashFiles('data_ingester/data_ingester_workspace/Cargo.lock') }}

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --manifest-path data_ingester/data_ingester_rust/Cargo.toml

      - name: cargo build
        run: cd data_ingester/data_ingester_workspace; cargo build --release --target=x86_64-unknown-linux-musl

      - name: cp bin
        run: cp data_ingester/data_ingester_workspace/target/x86_64-unknown-linux-musl/release/data_ingester_axum_entrypoint data_ingester/data_ingester_workspace/data_ingester_axum_entrypoint/function_zip

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7


      - name: Terraform version
        run: terraform -version

        # Terraform
      - name: Run terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: cd data_ingester/terraform/red; terraform init; terraform apply -auto-approve
